### ISSUE TITLE
Exception on Kirby 4

### ISSUE THREAD

**Issue by schrockwell** [johannschopplich/kirby-highlighter#21]
Is Kirby 4.x supported? I am getting the following error on Kirby 4.0 and 4.1.0-rc.2.

```
:  During inheritance of DOMDocument: Uncaught Whoops\Exception\ErrorException: Return type of JohannSchopplich\HTML5DOMDocument::loadHTML($source, $options = <expression>) should either be compatible with DOMDocument::loadHTML(string $source, int $options = 0): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in my-project/site/plugins/kirby-highlighter/classes/JohannSchopplich/HTML5DOMDocument.php:37
Stack trace:
#0 my-project/kirby/vendor/composer/ClassLoader.php(582): Whoops\Run->handleError(8192, 'Return type of ...', '/Users/rockwell...', 37)
#1 my-project/kirby/vendor/composer/ClassLoader.php(582): include()
#2 my-project/kirby/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}('/Users/rockwell...')
#3 my-project/site/plugins/kirby-highlighter/extensions/hooks.php(9): Composer\Autoload\ClassLoader->loadClass('JohannSchopplic...')
#4 [internal function]: Kirby\Cms\App->{closure}('<p>I spent a fe...')
#5 my-project/kirby/src/Toolkit/Controller.php(60): Closure->call(Object(Kirby\Cms\App), text: '<p>I spent a fe...')
#6 my-project/kirby/src/Cms/Event.php(139): Kirby\Toolkit\Controller->call(Object(Kirby\Cms\App), Array)
#7 my-project/kirby/src/Cms/App.php(225): Kirby\Cms\Event->call(Object(Kirby\Cms\App), Object(Kirby\Toolkit\Controller))
#8 my-project/kirby/src/Cms/App.php(876): Kirby\Cms\App->apply('kirbytext:after', Array, 'text')
#9 my-project/kirby/config/methods.php(399): Kirby\Cms\App->kirbytext('<p>I spent a fe...', Array)
#10 my-project/kirby/src/Content/Field.php(85): Kirby\Cms\Core->{closure}(Object(Kirby\Content\Field))
#11 my-project/kirby/config/blocks/markdown/markdown.php(2): Kirby\Content\Field->__call('kirbytext', Array)
#12 my-project/kirby/src/Filesystem/F.php(425): include('/Users/rockwell...')
#13 my-project/kirby/src/Filesystem/F.php(364): Kirby\Filesystem\F::loadIsolated('/Users/rockwell...', Object(Kirby\Cms\Block))
#14 my-project/kirby/src/Filesystem/F.php(372): Kirby\Filesystem\F::Kirby\Filesystem\{closure}()
#15 my-project/kirby/src/Toolkit/Tpl.php(36): Kirby\Filesystem\F::load('/Users/rockwell...', NULL, Array)
#16 my-project/kirby/src/Template/Snippet.php(172): Kirby\Toolkit\Tpl::load('/Users/rockwell...', Array)
#17 my-project/kirby/config/components.php(301): Kirby\Template\Snippet::factory('blocks/markdown', Array, false)
#18 my-project/kirby/src/Cms/App.php(1546): Kirby\Cms\Core->{closure}(Object(Kirby\Cms\App), 'blocks/markdown', Array, false)
#19 my-project/kirby/src/Cms/Block.php(232): Kirby\Cms\App->snippet('blocks/markdown', Array, true)
#20 my-project/kirby/src/Cms/Blocks.php(163): Kirby\Cms\Block->toHtml()
#21 [internal function]: Kirby\Cms\Blocks->Kirby\Cms\{closure}(Object(Kirby\Cms\Block))
#22 my-project/kirby/src/Toolkit/A.php(471): array_map(Object(Closure), Array)
#23 my-project/kirby/src/Cms/Blocks.php(163): Kirby\Toolkit\A::map(Array, Object(Closure))
#24 my-project/kirby/src/Cms/Blocks.php(39): Kirby\Cms\Blocks->toHtml()
#25 my-project/site/templates/post.php(5): Kirby\Cms\Blocks->__toString()
#26 my-project/kirby/src/Filesystem/F.php(425): include('/Users/rockwell...')
#27 my-project/kirby/src/Filesystem/F.php(364): Kirby\Filesystem\F::loadIsolated('/Users/rockwell...', Array)
#28 my-project/kirby/src/Filesystem/F.php(372): Kirby\Filesystem\F::Kirby\Filesystem\{closure}()
#29 my-project/kirby/src/Toolkit/Tpl.php(36): Kirby\Filesystem\F::load('/Users/rockwell...', NULL, Array)
#30 my-project/kirby/src/Template/Template.php(163): Kirby\Toolkit\Tpl::load('/Users/rockwell...', Array)
#31 my-project/kirby/src/Cms/Page.php(1017): Kirby\Template\Template->render(Array)
#32 my-project/kirby/src/Cms/App.php(775): Kirby\Cms\Page->render()
#33 my-project/kirby/src/Cms/App.php(1189): Kirby\Cms\App->io(Object(Kirby\Cms\Page))
#34 my-project/index.php(5): Kirby\Cms\App->render()
#35 my-project/kirby/router.php(14): require('/Users/rockwell...')
#36 {main} in 
```

**Comment by johannschopplich** [comment]
Hi there!
Unfortunately I'm no longer actively developing the highlighter plugin. You can book some consulting to let us find the bug. But since I don't use this plugin myself anymore, I probably won't take the time to take a look into the issue. I hope you understand that. 🙂 

PR is always welcome, of course. If you add support for Kirby 4, I will gladly merge it.

**Comment by schrockwell** [comment]
Understood!
